language: node_js
node_js:
- '8'
script: npm run build
deploy:
  provider: npm
  email: simbo@simbo.de
  api_key: "${NPM_API_KEY}"
  on:
    tags: true
env:
  global:
    secure: PLR/nkGOJa58kOvNzp/znY7lwNDi91jUrwWV0AfkshZHfrIxj8bqyVra4UGoSiamaWRsDPTvhfyoRkPvcDo0Epq1JjqEjQogWeilazTKFTCX7EoH6UGHq838E4XhWVvJgPbVJhnSH1XUV3H3Vvs6JjtjMwNOcW8wMq4BOlfqPehhizszP5KMqLkSs1bhH6Jil1TEqTxIWpod7QOrEjDrXHc4p2DoStEfFkY+PooFVqK0bivnGnV6jLBPa7TbxuZBklzFgmLQR1d59KiU5dt5G8GTt7M/CppleZnQ5ZY0Bh7VRffGjn/CCfoWxr69i75sZm1RnYQFuVbsplg8XQb7PrQ18NUjonCopiF2hYH/h8N7z4gMeEn6H+kkeBcabkdSk+unXVUqiLQ+ufzTeGOXUDSjQQze4rTLm9tPChoUG7/Li4dsZs6Jy7OTCkrE/k84L7MXljqVUV5i8UkeGicV6WJs+9Q2k399TIrV3Ji8GODeI9fpIYrpbFe9Ue1Ghfds37jvHwxfALX60dCBUktW2pOSiWH1QW1sMZiEIrNt5EDW6jEZl6Lzk5robY/EDJqqFXTKTMBFqzrpLb3yvf/IsuBCT9yuigEGZOJOY2cA1uVbVtVCabUjD6ZAI2mUsZBQG2SZrhzGwZy4p6KJJe5/msiepO3oi6GaUWRLKG90vXQ=
